engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      import/no-unresolved:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
         - javascript
  fixme:
    enabled: true
exclude_paths:
  - test/
