language: node_js
node_js:
  - "6"
  - "5"
  - "4"
env:
  - MYSQL_URI_TEST="mysql://root@localhost:3306/node_daemons_test"
  - NODE_ID=1
cache:
  directories:
    - node_modules
services:
  - mysql
before_script:
  - mysql -e 'create database node_daemons_test;'
branches:
  only:
    - master
