language: node_js
node_js:
  - "11"
  - "10"
  - "8"
  - "6"

services:
  - mysql

env:
  - CC_TEST_REPORTER_ID=f33acea34caf4303764b7d77cd78b0d328a3b6447d050723fc0ffeff2b031212
  - MYSQL_URI_TEST="mysql://root@localhost:3306/node_daemons_test"
  - NODE_ID="1"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - mysql -e 'create database node_daemons_test;'
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
